package com.shouyu.dframework.respository.criteria;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;

public abstract class Example<T extends AbstractCriteria> {
    private Class<T> tClass;
    private final static Logger LOGGER = LoggerFactory.getLogger(Example.class);
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    protected List<T> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    public Example() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    public List<T> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    public void or(T criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    public T or() {
        T criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    public  T createCriteria(Class<T> clazz) {
        this.tClass=clazz;
        T criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    protected T createCriteriaInternal() {
        T criteria = null;
        try {
            criteria = this.tClass.newInstance();
        } catch (InstantiationException e) {
            LOGGER.error("InstantiationException", e);
        } catch (IllegalAccessException e) {
            LOGGER.error("IllegalAccessException", e);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }
}
