package com.shouyu.dframework.infrastructure.repository.mysql;

import com.shouyu.dframework.entity.Entity;
import com.shouyu.dframework.respository.criteria.Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MybatisMapper<ID, T extends Entity> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    long countByExample(Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    int deleteByExample(Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    int deleteByPrimaryKey(ID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    List<T> selectByExample(Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    T selectByPrimaryKey(ID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    int updateByExampleSelective(@Param("record") T record, @Param("example") Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    int updateByExample(@Param("record") T record, @Param("example") Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_account
     *
     * @mbg.generated Sun Nov 21 13:08:05 CST 2021
     */
    int updateByPrimaryKey(T record);

}
